/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package swagger.code.generator.gradle.plugin

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'swagger.code.generator.gradle.plugin.greeting' plugin.
 */
class SwaggerCodeGeneratorGradlePluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("swagger.code.generator.gradle.plugin.SwaggerCodeGeneratorGradlePlugin")

        // Verify the result
        assertNotNull(project.tasks.findByName("genApiClient"))
    }
}
